[package]
name = "RustLearn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
serde_yaml = "0.9.21"
tokio = "1.28.2"
#fontfinder = "1.5.0"
once_cell = "1.17.2"